version: '3.7'

services:
  api:
    image: 'balboa-api'
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: balboa-api
    ports:
      - 7000:7000
    env_file: .env
    volumes:
      - ./src:/api/src
    networks:
      - np-network
    depends_on:
      - migration

  postgres:
    image: postgres:14.1-alpine
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - np-network

  migration:
    env_file: .env
    build:
      context: .
    command: ['npm', 'run', 'migration:run']
    networks:
      - np-network
    depends_on:
      - postgres

volumes:
  postgres:
networks:
  np-network:
